version: "3.8"
volumes:
        shared-workspace:
                name: "hadoop-distributed-file-system"
                driver: local
services:
        jupyterlab:
                image: andreper/jupyterlab:latest
                container_name: jupyterlab
                ports:
                  - 8888:8888
                volumes:
                  - shared-workspace:/opt/workspace
        spark-master:
                image: andreper/spark-master:latest
                container_name: spark-master
                ports:
                  - 8080:8080
                  - 7077:7077
                volumes:
                  - shared-workspace:/opt/workspace
        spark-worker-1:
                image: andreper/spark-worker:latest
                container_name: spark-worker-1
                environment:
                  - SPARK_WORKER_CORES=1
                  - SPARK_WORKER_MEMORY=512m
                ports:
                  - 8081:8081
                volumes:
                  - shared-workspace:/opt/workspace
                depends_on:
                  - spark-master
        spark-worker-2:
                image: andreper/spark-worker:latest
                container_name: spark-worker-2
                environment:
                  - SPARK_WORKER_CORES=1
                  - SPARK_WORKER_MEMORY=512m
                ports:
                  - 8082:8081
                volumes:
                  - shared-workspace:/opt/workspace
                depends_on:
                  - spark-master
